language: node_js
cache:
  yarn: true
services:
- docker
deploy:
  provider: script
  script: bash docker_push.sh
  on:
    branch: master
env:
  global:
  - secure: lIuf3EeuZRp9xc6d8VZh8OjtRoeA5iElxzGp3IKzZv5Mb2QcJq2C5zA9tuvA2CtwLW5bjh2rBdfXnrFXJPpVRzjHpISzgAq0Vef0Ai/LVKz434fFZr2WEeT1glPVFjE//DN3xKuM4uoe8s3orzctMNHVHVbyjMTfgmdRDaCFUmD73JLcVkszvNq33SmOLufdU/IZWOj7o7c3m8OD4KBxds0Rh4+yF1iwQ9W/+CBHOeKByvAG3fqYclXOUyzbagSX2AZYultqqcN/M3q+TyPAe+OyFda/aU+Qd9Bj+62W63rZWYhhAPwP2Nn+A1v4bmyrmVadUliWiQoJJcmDs169Qu88tJN/WP7wUyp6V5PaLFb8U3w7SA9R6QZmgjNHMIz3FJHlXOizIU1PHfWpYcM/htMMTsfNSS4werPcA8fdCBR1rzJtQkBaUVH6K7FtXGOJwBob7KkaDr3gKue0JBS7DXarqL9S6r/3bwfXVNW6XL/SvchilHv/uagoZIP7mJy5rXQhwj+8K4nWneU1xySzLxieGJFVg63K2Ws10DvzV+8yrQbTtdTN7a0qYYhad7uOwvLCEbA/yjYjXgRkezG03aLawwO0MWYFN2UPdXrdncSM+Yg6M0Dp21Mo6qU3YfDZnzikkuF8SIR//Rik9ieaP6odGJULL5HWJZRbaCZUbpo=
  - secure: hgK2WNQWjcMeEl8XcfdmEc6QzJf0rpew/VBKOmyr8URWcFbbvLY0AHDRmQ2LtJXKLtxZjLUfarJJSBkBTTZaBWaHRFQs2ERZ6hwYq82lUdIimXvWPvNMogjCIMHWfq6by/txybqITZWoR4R8prkr3Mys8N+LoedUmF89bod1urJCllgL7pd6RilSAulaU0oTlmEWtsxonkvYTX98YPfLKUQiH91gXvnjPTVP+AczZy6lGGXJEV88bwVb6B0ChBNXqz6GrhGJE8kMeWyY/1t54mqEwHFOZHHLsZfvzTr8Ad/xEs3RQgla0s/wfxyEjI1jjQR0ANtqTPdCezL1xMNiSrYLnNJRc2I90IoemwNdFu99ayiQqu7NprH066bO2gcUjePDDjY7wSV3XE7y5hSHMa9J7BHcvcUDotSmiptUoT6WS5fFnLW6I3wOMshoABcIYHfpjiLRlGwUwUYgtyWsPDNlclNY2w2mQlw8AvQ5VGypdki5MfKdWyW4AdoVeOkNSA38y3qW0t7IDj++dHX1y6UztTRvoN/eBjN6ewWemArsGLY4lvPGMpMlsvK52H0j440kwr8YRk0XiuK8PxM1f5MpxM5Zp99+9CTpLcoRp+lsH8VAZm6jNxT803Mcllbb25A9l2OMcxMt+Vdc0cBb1BnAJ4sKnGd5KXA6wLVsrCw=
